//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produit()
        {
            this.ligne_de_commande = new HashSet<ligne_de_commande>();
            this.ligne_de_livraison = new HashSet<ligne_de_livraison>();
        }
    
        public int produit_id { get; set; }
        public string produit_nomcourt { get; set; }
        public string produit_nom { get; set; }
        public string produit_photo { get; set; }
        public Nullable<decimal> produit_prixachat { get; set; }
        public bool produit_etat { get; set; }
        public Nullable<decimal> produit_prixht { get; set; }
        public bool produit_validite { get; set; }
        public int ss_rubrique_id { get; set; }
        public int fournisseur_id { get; set; }
        public int tva_id { get; set; }
    
        public virtual fournisseur fournisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligne_de_commande> ligne_de_commande { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligne_de_livraison> ligne_de_livraison { get; set; }
        public virtual sous_rubrique sous_rubrique { get; set; }
        public virtual tva tva { get; set; }
    }
}
