//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public string util_Identifiant { get; set; }
        public string util_MotPasse { get; set; }
        public string util_Email { get; set; }
        public System.DateTime util_DateInscrip { get; set; }
        public Nullable<bool> util_Confirm { get; set; }
        public string util_Type { get; set; }
        public int util_IdPerso { get; set; }
        public string util_Nom { get; set; }
        public string util_Prenom { get; set; }
    }
}
