//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilRougeORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class villagegreenEntities : DbContext
    {
        public villagegreenEntities()
            : base("name=villagegreenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bon_livraison> bon_livraison { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<commande> commande { get; set; }
        public virtual DbSet<commercial> commercial { get; set; }
        public virtual DbSet<fournisseur> fournisseur { get; set; }
        public virtual DbSet<ligne_de_commande> ligne_de_commande { get; set; }
        public virtual DbSet<ligne_de_livraison> ligne_de_livraison { get; set; }
        public virtual DbSet<produit> produit { get; set; }
        public virtual DbSet<rubrique> rubrique { get; set; }
        public virtual DbSet<sous_rubrique> sous_rubrique { get; set; }
        public virtual DbSet<tva> tva { get; set; }
    }
}
